"""Tests for the async HTTP client.

Focus areas:
* Idempotency-Key validation regex.
* Idempotency-Key sent on submit_url / submit_file (auto-generated by default).
* Authorization header is X-API-Key only — never Bearer for the API key.
* Retry on 429 then success.
* Backend error code mapping.
"""

from __future__ import annotations

import re

import pytest

from whipscribe_mcp.client import (
    _IDEMPOTENCY_KEY_RE,
    WhipscribeClient,
    _validate_idempotency_key,
    generate_idempotency_key,
)
from whipscribe_mcp.errors import ToolError


class TestIdempotencyKey:
    def test_generated_key_matches_pattern(self) -> None:
        for _ in range(20):
            key = generate_idempotency_key()
            assert _IDEMPOTENCY_KEY_RE.match(key), key

    @pytest.mark.parametrize(
        "key",
        [
            "short-key",
            "a" * 255,
            "AbCd_1234",
            "u-90abcdef",
            "key:with/slashes.dots-and_underscores",
        ],
    )
    def test_validate_accepts_documented_charset(self, key: str) -> None:
        _validate_idempotency_key(key)

    @pytest.mark.parametrize(
        "key",
        ["", "has whitespace", "newline\nhere", "tab\there", "a" * 256, "weird*char"],
    )
    def test_validate_rejects_invalid(self, key: str) -> None:
        with pytest.raises(ToolError) as exc_info:
            _validate_idempotency_key(key)
        assert exc_info.value.code == "invalid_input"


class TestAuthHeader:
    def test_no_auth_header_when_no_key(self) -> None:
        client = WhipscribeClient(api_base="https://example.local/v1")
        try:
            assert "X-API-Key" not in client._client.headers
            assert "Authorization" not in client._client.headers
        finally:
            # Sync close is fine for an unused AsyncClient.
            pass

    def test_x_api_key_only_when_key_set(self) -> None:
        client = WhipscribeClient(
            api_base="https://example.local/v1",
            api_key="sk-test-key",
        )
        assert client._client.headers.get("X-API-Key") == "sk-test-key"
        # Bearer is reserved for Firebase id-tokens per the API docs;
        # the API key must NEVER be sent as Bearer.
        auth_header = client._client.headers.get("Authorization", "")
        assert "Bearer" not in auth_header
        assert "sk-test-key" not in auth_header


class TestSubmitUrl:
    @pytest.mark.asyncio
    async def test_sends_idempotency_key(self, httpx_mock) -> None:  # type: ignore[no-untyped-def]
        httpx_mock.add_response(
            method="POST",
            url="https://example.local/v1/transcribe/url",
            json={"job_id": "abc123", "status": "queued"},
        )
        async with WhipscribeClient(api_base="https://example.local/v1") as client:
            result = await client.submit_url("https://example.com/audio.mp3")

        assert result["job_id"] == "abc123"
        request = httpx_mock.get_requests()[0]
        sent_key = request.headers.get("Idempotency-Key")
        assert sent_key is not None and _IDEMPOTENCY_KEY_RE.match(sent_key)

    @pytest.mark.asyncio
    async def test_caller_provided_key_takes_precedence(self, httpx_mock) -> None:  # type: ignore[no-untyped-def]
        httpx_mock.add_response(
            method="POST",
            url="https://example.local/v1/transcribe/url",
            json={"job_id": "abc", "status": "queued"},
        )
        async with WhipscribeClient(api_base="https://example.local/v1") as client:
            await client.submit_url(
                "https://example.com/a.mp3",
                idempotency_key="caller-supplied-key-1",
            )
        request = httpx_mock.get_requests()[0]
        assert request.headers.get("Idempotency-Key") == "caller-supplied-key-1"

    @pytest.mark.asyncio
    async def test_invalid_caller_key_raises(self, httpx_mock) -> None:  # type: ignore[no-untyped-def]
        async with WhipscribeClient(api_base="https://example.local/v1") as client:
            with pytest.raises(ToolError) as exc:
                await client.submit_url(
                    "https://example.com/a.mp3",
                    idempotency_key="has spaces in it",
                )
        assert exc.value.code == "invalid_input"


class TestRetryAndErrors:
    @pytest.mark.asyncio
    async def test_retries_on_429_then_succeeds(self, httpx_mock) -> None:  # type: ignore[no-untyped-def]
        httpx_mock.add_response(
            method="GET",
            url="https://example.local/v1/jobs/abc",
            status_code=429,
            headers={"Retry-After": "0"},
        )
        httpx_mock.add_response(
            method="GET",
            url="https://example.local/v1/jobs/abc",
            json={"status": "queued"},
        )
        async with WhipscribeClient(api_base="https://example.local/v1") as client:
            result = await client.get_job_status("abc")
        assert result["status"] == "queued"
        assert len(httpx_mock.get_requests()) == 2

    @pytest.mark.asyncio
    async def test_backend_code_maps_to_error(self, httpx_mock) -> None:  # type: ignore[no-untyped-def]
        httpx_mock.add_response(
            method="GET",
            url="https://example.local/v1/jobs/missing",
            status_code=404,
            json={"error": "Job not found", "code": "NOT_FOUND"},
        )
        async with WhipscribeClient(api_base="https://example.local/v1") as client:
            with pytest.raises(ToolError) as exc:
                await client.get_job_status("missing")
        assert exc.value.code == "job_not_found"
        assert exc.value.message == "Job not found"

    @pytest.mark.asyncio
    async def test_402_maps_to_quota_exceeded(self, httpx_mock) -> None:  # type: ignore[no-untyped-def]
        httpx_mock.add_response(
            method="GET",
            url="https://example.local/v1/me",
            status_code=402,
        )
        async with WhipscribeClient(api_base="https://example.local/v1") as client:
            with pytest.raises(ToolError) as exc:
                await client.whoami()
        assert exc.value.code == "quota_exceeded"


class TestClaimTokenHeader:
    @pytest.mark.asyncio
    async def test_x_claim_token_sent_when_provided_to_get_job_status(
        self,
        httpx_mock,  # type: ignore[no-untyped-def]
    ) -> None:
        httpx_mock.add_response(
            method="GET",
            url="https://example.local/v1/jobs/anon-job",
            json={"status": "processing"},
        )
        async with WhipscribeClient(api_base="https://example.local/v1") as client:
            await client.get_job_status("anon-job", claim_token="tok-xyz-789")
        request = httpx_mock.get_requests()[0]
        assert request.headers.get("X-Claim-Token") == "tok-xyz-789"

    @pytest.mark.asyncio
    async def test_x_claim_token_sent_when_provided_to_get_transcript(
        self,
        httpx_mock,  # type: ignore[no-untyped-def]
    ) -> None:
        httpx_mock.add_response(
            method="GET",
            url=re.compile(r"^https://example.local/v1/jobs/anon-job/result\?format=txt$"),
            text="hello",
        )
        async with WhipscribeClient(api_base="https://example.local/v1") as client:
            await client.get_transcript("anon-job", format="txt", claim_token="tok-xyz-789")
        request = httpx_mock.get_requests()[0]
        assert request.headers.get("X-Claim-Token") == "tok-xyz-789"

    @pytest.mark.asyncio
    async def test_no_claim_token_header_when_omitted(
        self,
        httpx_mock,  # type: ignore[no-untyped-def]
    ) -> None:
        httpx_mock.add_response(
            method="GET",
            url="https://example.local/v1/jobs/keyed-job",
            json={"status": "done"},
        )
        async with WhipscribeClient(
            api_base="https://example.local/v1",
            api_key="sk-test",
        ) as client:
            await client.get_job_status("keyed-job")
        request = httpx_mock.get_requests()[0]
        assert "X-Claim-Token" not in request.headers


class TestGetTranscript:
    @pytest.mark.asyncio
    async def test_txt_returns_str(self, httpx_mock) -> None:  # type: ignore[no-untyped-def]
        httpx_mock.add_response(
            method="GET",
            url=re.compile(r"^https://example.local/v1/jobs/job1/result\?format=txt$"),
            text="hello world",
        )
        async with WhipscribeClient(api_base="https://example.local/v1") as client:
            body = await client.get_transcript("job1", format="txt")
        assert body == "hello world"

    @pytest.mark.asyncio
    async def test_json_returns_dict(self, httpx_mock) -> None:  # type: ignore[no-untyped-def]
        httpx_mock.add_response(
            method="GET",
            url=re.compile(r"^https://example.local/v1/jobs/job1/result\?format=json$"),
            json={"text": "hello", "segments": []},
        )
        async with WhipscribeClient(api_base="https://example.local/v1") as client:
            body = await client.get_transcript("job1", format="json")
        assert isinstance(body, dict)
        assert body["text"] == "hello"
